<?php

namespace HelpdeskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends EntityRepository
{
}
