<?php

namespace HelpdeskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* OperatorsRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class OperatorsRepository extends EntityRepository
{
  public function getUsersByName($name){
    $result = $this->getEntityManager()->getRepository("HelpdeskBundle:User")->createQueryBuilder('u')
    ->andWhere('u.username LIKE :name')
    ->orWhere('u.firstname LIKE :name')
    ->orWhere('u.surname LIKE :name')
    ->setParameter('name', '%'.$name. '%')
    ->orderBy('u.firstname', 'ASC')
    ->setMaxResults('5')
    ->getQuery()
    ->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);

    return $result;
  }

  public function getCategoriesForOperators(){
    $result = $this->getEntityManager()->getRepository("HelpdeskBundle:Categories")->createQueryBuilder('u')
    ->getQuery()
    ->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);

    return $result;
  }
}
